import { NextResponse } from 'next/server';
import { gzipSync } from 'node:zlib';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type PluginFile = { path: string; content: string };

function tarHeader(name: string, size: number): Buffer {
  const header = Buffer.alloc(512, 0);
  const write = (value: string, offset: number, length: number) => {
    const bytes = Buffer.from(value, 'utf8');
    bytes.copy(header, offset, 0, Math.min(bytes.length, length));
  };
  const octal = (value: number, length: number) => value.toString(8).padStart(length - 1, '0') + '\0';
  write(name, 0, 100);
  write(octal(0o644, 8), 100, 8);
  write(octal(0, 8), 108, 8);
  write(octal(0, 8), 116, 8);
  write(octal(size, 12), 124, 12);
  write(octal(Math.floor(Date.now() / 1000), 12), 136, 12);
  for (let i = 148; i < 156; i++) header[i] = 0x20;
  write('0', 156, 1);
  write('ustar\0', 257, 6);
  write('00', 263, 2);
  write('sameer', 265, 32);
  write('sameer', 297, 32);
  write('0000000', 329, 8);
  write('0000000', 337, 8);
  const checksum = header.reduce((sum, byte) => sum + byte, 0);
  write(checksum.toString(8).padStart(6, '0') + '\0 ', 148, 8);
  return header;
}

function createTarGz(files: PluginFile[]) {
  const chunks: Buffer[] = [];
  for (const file of files) {
    const content = Buffer.from(file.content, 'utf8');
    chunks.push(tarHeader(file.path, content.length), content);
    const padding = (512 - (content.length % 512)) % 512;
    if (padding) chunks.push(Buffer.alloc(padding));
  }
  chunks.push(Buffer.alloc(1024));
  return gzipSync(Buffer.concat(chunks), { level: 6 });
}

function safeSlug(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'github-workspace';
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const name = String(body?.name || 'GitHub Workspace').trim().slice(0, 64);
    const description = String(body?.description || 'Use GitHub through the hosted GitHub MCP server.').trim().slice(0, 500);
    const slug = safeSlug(String(body?.slug || name));
    const toolset = ['all', 'default', 'readonly'].includes(String(body?.toolset)) ? String(body.toolset) : 'all';

    const mcpUrl = toolset === 'readonly'
      ? 'https://api.githubcopilot.com/mcp/x/all/readonly'
      : toolset === 'default'
        ? 'https://api.githubcopilot.com/mcp/'
        : 'https://api.githubcopilot.com/mcp/x/all';

    const manifest = {
      '$schema': 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
      name: slug,
      version: '1.0.0',
      description,
      author: { name: 'Sameer AI Workspace' },
      license: 'MIT',
      keywords: ['github', 'git', 'repositories', 'issues', 'pull-requests', 'code'],
      mcpServers: './mcp.json',
      extensions: {
        'com.openai': {
          interface: {
            displayName: name,
            shortDescription: 'GitHub repository, issue, pull request, and code workflows.',
            longDescription: description,
            developerName: 'Sameer AI Workspace',
            category: 'Developer tools',
            capabilities: ['Repositories', 'Issues', 'Pull Requests', 'Code', 'Actions'],
            defaultPrompt: [
              'Inspect my GitHub repository and summarize what needs attention.',
              'Review the latest pull requests and explain the important changes.',
              'Find the relevant code and propose a focused fix.'
            ]
          }
        }
      }
    };

    const mcp = {
      '$schema': 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json',
      mcpServers: {
        github: { type: 'streamable-http', url: mcpUrl }
      }
    };

    const compatibilityManifest = {
      name: slug,
      version: '1.0.0',
      description,
      skills: './skills/',
      mcpServers: './.mcp.json'
    };

    const skill = \`---
name: github-workflows
description: Use the GitHub MCP server for repository, issue, pull request, code, and workflow tasks. Confirm destructive actions before executing them.
---

Use the github MCP server when the user asks about GitHub repositories, issues, pull requests, code, Actions, or related GitHub resources. Prefer targeted searches and inspect relevant resources before making changes. Before destructive or externally visible actions such as merging, closing, deleting, or creating content, confirm the intended target and scope with the user.
\`;

    const readme = \`# \${name}

This plugin connects the workspace to GitHub's hosted Remote MCP server.

- MCP endpoint: \${mcpUrl}
- Authentication: performed by the MCP host (OAuth or another supported GitHub access token).
- Included skill: github-workflows

Generated by Sameer AI Workspace Plugin Creator.
\`;

    const files: PluginFile[] = [
      { path: slug + '/plugin.json', content: JSON.stringify(manifest, null, 2) + '\\n' },
      { path: slug + '/mcp.json', content: JSON.stringify(mcp, null, 2) + '\\n' },
      { path: slug + '/.mcp.json', content: JSON.stringify(mcp, null, 2) + '\\n' },
      { path: slug + '/.codex-plugin/plugin.json', content: JSON.stringify(compatibilityManifest, null, 2) + '\\n' },
      { path: slug + '/skills/github-workflows/SKILL.md', content: skill },
      { path: slug + '/README.md', content: readme },
    ];

    const archive = createTarGz(files);
    return NextResponse.json({ success: true, filename: slug + '.tar.gz', archiveBase64: archive.toString('base64'), files: files.map((file) => file.path), mcpUrl, toolset });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: String(error?.message || 'Plugin creation failed.') }, { status: 400 });
  }
}
