import { NextResponse } from 'next/server';
import { gzipSync } from 'node:zlib';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type PluginFile = { path: string; content: string };

function tarHeader(name: string, size: number): Buffer {
  const header = Buffer.alloc(512, 0);
  const write = (value: string, offset: number, length: number) => {
    const bytes = Buffer.from(value, 'utf8');
    bytes.copy(header, offset, 0, Math.min(bytes.length, length));
  };
  const octal = (value: number, length: number) => value.toString(8).padStart(length - 1, '0') + '\0';
  write(name, 0, 100);
  write(octal(0o644, 8), 100, 8);
  write(octal(0, 8), 108, 8);
  write(octal(0, 8), 116, 8);
  write(octal(size, 12), 124, 12);
  write(octal(Math.floor(Date.now() / 1000), 12), 136, 12);
  for (let i = 148; i < 156; i++) header[i] = 0x20;
  write('0', 156, 1);
  write('ustar\0', 257, 6);
  write('00', 263, 2);
  write('sameer', 265, 32);
  write('sameer', 297, 32);
  write('0000000', 329, 8);
  write('0000000', 337, 8);
  const checksum = header.reduce((sum, byte) => sum + byte, 0);
  write(checksum.toString(8).padStart(6, '0') + '\0 ', 148, 8);
  return header;
}

function createTarGz(files: PluginFile[]) {
  const chunks: Buffer[] = [];
  for (const file of files) {
    const content = Buffer.from(file.content, 'utf8');
    chunks.push(tarHeader(file.path, content.length), content);
    const padding = (512 - (content.length % 512)) % 512;
    if (padding) chunks.push(Buffer.alloc(padding));
  }
  chunks.push(Buffer.alloc(1024));
  return gzipSync(Buffer.concat(chunks), { level: 6 });
}

function safeSlug(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'github-workspace';
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const name = String(body?.name || 'My MCP Plugin').trim().slice(0, 64);
    const description = String(body?.description || 'Connect this workspace to a remote MCP service.').trim().slice(0, 500);
    const slug = safeSlug(String(body?.slug || name));
    const authMode = ['oauth', 'api_token', 'client_credentials', 'none'].includes(String(body?.authMode)) ? String(body.authMode) : 'oauth';
    const serverUrl = String(body?.serverUrl || '').trim();
    const setupUrl = String(body?.setupUrl || '').trim();
    if (!serverUrl || !/^https?:\/\//i.test(serverUrl)) throw new Error('A valid HTTP/HTTPS MCP server URL is required.');

    const mcpUrl = serverUrl;

    const manifest = {
      '$schema': 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
      name: slug,
      version: '1.0.0',
      description,
      author: { name: 'Sameer AI Workspace' },
      license: 'MIT',
      keywords: ['mcp', 'connector', 'integration', authMode],
      mcpServers: './mcp.json',
      extensions: {
        'com.openai': {
          interface: {
            displayName: name,
            shortDescription: 'Remote MCP connector for this workspace.',
            longDescription: description,
            developerName: 'Sameer AI Workspace',
            category: 'Developer tools',
            capabilities: ['Remote MCP', 'Tool Discovery', 'Tool Execution', 'Authentication'],
            defaultPrompt: [
              'Discover the available tools from this connector and summarize what I can do with it.',
              'Use the connector to complete the requested task and explain the result.',
              'Inspect the connected service and propose a focused next step.'
            ]
          }
        }
      }
    };

    const mcp = {
      '$schema': 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json',
      mcpServers: {
        [slug]: { type: 'streamable-http', url: mcpUrl }
      }
    };

    const compatibilityManifest = {
      name: slug,
      version: '1.0.0',
      description,
      skills: './skills/',
      mcpServers: './.mcp.json'
    };

    const skill = `---
name: remote-mcp-workflows
description: Use this remote MCP connector for the provider's tools. Confirm destructive or externally visible actions before executing them.
---

Use the remote MCP server when the user asks for actions or information supported by this connector. Prefer targeted tool discovery and inspect relevant resources before making changes. Before destructive or externally visible actions, confirm the intended target and scope with the user.
`;

    const readme = `# ${name}

This plugin connects the workspace to a remote MCP server.

- MCP endpoint: ${mcpUrl}
- Authentication mode: ${authMode}
- Credential/setup page: ${setupUrl || 'Provided by the service operator'}
- Included skill: remote-mcp-workflows

Generated by Sameer AI Workspace Plugin Creator.
`;

    const files: PluginFile[] = [
      { path: slug + '/plugin.json', content: JSON.stringify(manifest, null, 2) + '\\n' },
      { path: slug + '/mcp.json', content: JSON.stringify(mcp, null, 2) + '\\n' },
      { path: slug + '/.mcp.json', content: JSON.stringify(mcp, null, 2) + '\\n' },
      { path: slug + '/.codex-plugin/plugin.json', content: JSON.stringify(compatibilityManifest, null, 2) + '\\n' },
      { path: slug + '/skills/remote-mcp-workflows/SKILL.md', content: skill },
      { path: slug + '/README.md', content: readme },
    ];

    const archive = createTarGz(files);
    return NextResponse.json({ success: true, filename: slug + '.tar.gz', archiveBase64: archive.toString('base64'), files: files.map((file) => file.path), mcpUrl, authMode });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: String(error?.message || 'Plugin creation failed.') }, { status: 400 });
  }
}
